vim.api.nvim_set_hl(0, "CustomCmpMenu", { bg = "NONE", fg = "white" })
vim.api.nvim_set_hl(0, "CustomCmpCursorLine", { bg = "#34425e", fg = "white" })

vim.api.nvim_set_hl(0, "CmpItemAbbr", { fg = "#6471c2" })
vim.api.nvim_set_hl(0, "CmpItemAbbrMatch", { fg = "#ffffff" })
vim.api.nvim_set_hl(0, "CmpItemAbbrMatchFuzzy", { fg = "#aeaeae" })
vim.api.nvim_set_hl(0, "CmpItemAbbrDeprecated", { fg = "#b77979" })

vim.api.nvim_set_hl(0, "CmpItemMenu", { fg = "#c792ea" })
vim.api.nvim_set_hl(0, "CmpItemKindClass", { fg = "#ff5555" })
vim.api.nvim_set_hl(0, "CmpItemKindConstructor", { fg = "#a5f725" })
vim.api.nvim_set_hl(0, "CmpItemKindKeyword", { fg = "#ff8754" })
vim.api.nvim_set_hl(0, "CmpItemKindFunction", { fg = "#8be9fd" })
vim.api.nvim_set_hl(0, "CmpItemKindMethod", { fg = "#d46ffa" })
vim.api.nvim_set_hl(0, "CmpItemKindModule", { fg = "#f78f25" })
vim.api.nvim_set_hl(0, "CmpItemKindSnippet", { fg = "#9b59b6" })
vim.api.nvim_set_hl(0, "CmpItemKindText", { fg = "#f7dc6f" })
vim.api.nvim_set_hl(0, "CmpItemKindVariable", { fg = "#f1fa8c" })
vim.api.nvim_set_hl(0, "CmpItemKindStruct", { fg = "#e17ad9" })
vim.api.nvim_set_hl(0, "CmpItemKindConstant", { fg = "#50fa7b" })
vim.api.nvim_set_hl(0, "CmpItemKindField", { fg = "#50fa7b" })
vim.api.nvim_set_hl(0, "CmpItemKindInterface", { fg = "#FFC300" })
vim.api.nvim_set_hl(0, "CmpItemKindEnum", { fg = "#5573f4" })
vim.api.nvim_set_hl(0, "NotifyBackground", { bg = "#000000" })
